DROP DATABASE IF EXISTS gestionCoches;
CREATE DATABASE  gestionCoches;
USE gestionCoches;
CREATE TABLE  coche (
	cocheID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	matricula VARCHAR(22) DEFAULT NULL,
	marca VARCHAR(100) DEFAULT NULL,
	modelo VARCHAR(100) DEFAULT NULL,
	tipo VARCHAR(100) DEFAULT NULL
);